### ISSUE TITLE
Update SONAR to user original driver

### ISSUE THREAD

**Issue by kercos** [CreativeRobotics/EnactiveTorchRT2b#5]
SONAR original driver not being used and not reading incoming serial bytes.

**Comment by CreativeRobotics** [comment]
SONAR will not work with serial because the serial data is inverted - it appears the Maxbotics SONAR module outputs serial data at logic level, but inverted as if sent via RS232. The SERCOM hardware module  cannot be configured to read inverted serial values so the only way to make this work is with additional hardware to invert the SONAR serial stream.

The default SONAR data read mode is to read PWM pulse lengths. The SONAR module outputs a PWM signal with a pulse of 147us per inch. This is read using interrupts to capture the pulse length, and is converted to cm.
